apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: sa-64-frontend
        image: 3mper0r/sa-64-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_SERVER
          value: "http://10.105.27.11"
        - name: REACT_APP_BACKEND_PORT
          value: "30201"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30202