apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: sa-64-backend
        image: 3mper0r/sa-64-backend
        ports:
        - containerPort: 8080
        env:
        - name: DB_MONGO_USER
          value: "mai"
        - name: DB_MONGO_PASS
          value: "P%40ssw0rd"
        - name: DB_MONGO_URL
          value: "mongodb-sfs-0"
        - name: DB_MONGO_PORT
          value: "27017"
        - name: DB_MONGO_NAME
          value: "sa-64"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080