apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017